### ISSUE TITLE
FTP upload won't accept any URL

### ISSUE THREAD

**Issue by fcpwiz** [zlepper/go-modpack-packer#10]
No matter what the FTP line won't accept and think it's invalid.
<img width="465" alt="modpack_helper_-_fluxx" src="https://cloud.githubusercontent.com/assets/2921172/17035888/da2d4efc-4f57-11e6-8338-7b1e45a6f97b.png">

**Comment by zlepper** [comment]
Fixed. It now takes an input of format:

`host:port`

Both the `host` and the `port` has to be specified.

**Comment by fcpwiz** [comment]
Ah great, thanks!
