### ISSUE TITLE
[1.0.19] Backend just exploded Error

### ISSUE THREAD

**Issue by Alaberti** [zlepper/go-modpack-packer#18]
Gives me backend exploded message and says to check the log: http://pastebin.com/raw/tMip9g2b

**Comment by zlepper** [comment]
That is certainly interesting..
Can you try deleting the %appdata%/ModpackPacker/modpacks.json file, and see if it corrects the issue?

**Comment by Alaberti** [comment]
That worked like a charm, thanks!
