### ISSUE TITLE
[1.0.19] Background Process Crashes during solder linking process

### ISSUE THREAD

**Issue by Alaberti** [zlepper/go-modpack-packer#19]
Log: http://pastebin.com/raw/8Yb1n7Wg

After packing the mods and ensuring they're on the ftp server correctly, I click continue to have the files linked to solder. Within seconds I get an crash notification.

**Comment by zlepper** [comment]
You have the solder link wrong, it should not be set to solder.whatever/api, but just to solder.whatever.

If changing that fixes it, please leave the bug report open, and I'll make sure to enforce it codewise.

**Comment by Alaberti** [comment]
That does seem to have fixed that issue - I had /api at the end because when I would use the built-in solder connection test, I would on get positive output with that tagged to the end.

However, now it crashes for a different reason: http://pastebin.com/raw/DDgWzpDX. Looks like it might be making too many requests in too short a time? 

Edit: I see the updated mods on solder, so they are linking at least.

**Comment by zlepper** [comment]
What operating system are you on? You seem to not quite be on the latest version which is 1.0.24, which I published earlier today. 

Edit: You can get it from here: http://zlepper.dk:3215/releases/stable
You seem to have been downloading the version that is on github (Which was just a test actually, and not the actual release process)

**Comment by Alaberti** [comment]
Windows 10. I didn't even notice the update notification, I will let that run and see where we go from there.

**Comment by zlepper** [comment]
I don't know if that will fix the other issue you sent (I doubt it), but it does provide slightly more info in the log.

**Comment by Alaberti** [comment]
Finished updating, cleared log, ran again. Same problem - hope this info helps: http://pastebin.com/raw/X50kcpnu

Edit: Could you do some input validation to see if bad data comes in, pause the program for a moment, and try again?

**Comment by Alaberti** [comment]
Looks like you could do some input validation to see if bad data comes in, pause the program for a moment, and try again?

**Comment by zlepper** [comment]
The only thing I can imagine that would cause that issue is if the actual modfile for some reason hasn't been uploaded, which is then, causing solder to not be able to hash the file, and then I can't add it to the modpack. So best I might be able to do is fail early after actually adding the mod version to solder, and then checking if it is actually there, and then error out if it's not.

**Comment by Alaberti** [comment]
New log: http://pastebin.com/raw/fqFGzN0E. I changed around some of my information, verified the integrity of every single mod, re-uploaded everything. 

Previously it was trying to make a build that didn't exist on a pack that also didn't exist - I had incorrectly tried to link the packer to the solder NAME not the MODSLUG so that was my bad. The mods are linking, it just crashes randomly after a point.

Edit: Started a fresh build, verified that it is a specific mod (Think Big Core) causing this specific issue, if I can address that and it goes through, I think this issue will be closable.

**Comment by Alaberti** [comment]
Got it! Something about that mod kept breaking everything, but taking it out removes the problem.

**Comment by zlepper** [comment]
Well, modpack packer should actually be creating both modpack, build and anything else that is missing in solder, so i don't really know why removing a single mod could be fixing the issue...

Any chance you can ship me the minecraft instance you are building from, and a video/screenshots that shows all your configuration, and how you step through everything? That way I might be able to reproduce something?

**Comment by Alaberti** [comment]
Sure, I'll work on it after work today

**Comment by zlepper** [comment]
I have just uploaded a new version, which might have the fix for the issue you reported, it does at least fix a crash around that area of the code, so it might help with your issue too. 

If this helped, then i have a question, how many mods does the pack you were attempting to pack have?

**Comment by Alaberti** [comment]
Sorry, I completely forgot about this after it was all up and working. The pack has about 146 mods in it, mostly small client-side tweaks. http://repo.getmodding.com/mods/aeronauts-resources/aeronauts-resources-1.10.2-Freedom.zip Here is the version I was working from.

Really, the only thing I was doing wrong before (besides the wrong solder link apparently) was, for the mod name in modpacker I was using the /actual/ name of the modpack, NOT the modpack slug. It never did find the build, and while it said it was making one I never saw it happen.

**Comment by zlepper** [comment]
> Really, the only thing I was doing wrong before (besides the wrong solder link apparently) was, for the mod name in modpacker I was using the /actual/ name of the modpack, NOT the modpack slug. It never did find the build, and while it said it was making one I never saw it happen.

hmm, it should be allowing the use of the actual name of the pack. I will go look through and see if I can find any specific issue related to this.

**Comment by Alaberti** [comment]
Just wanted to bring this to your attention: when I upload/link to solder, using the modpacker tool, it only seems to add the new mods to the pack - if I have say blood magic v 1.0 and I'm updating to 1.1, it will not change the version on my pack to 1.1. It does still link it to solder so I just change it via drop-down manually. Just something I thought you might be interested in. Your tool really has saved hours of my life, so it's not a big issue compared to "the old ways."
