### ISSUE TITLE
[2.0.1] Mods pack but continue option (solder integration) does not advance

### ISSUE THREAD

**Issue by Alaberti** [zlepper/go-modpack-packer#21]
![continue](https://user-images.githubusercontent.com/10929796/29745385-cf083c22-8a7e-11e7-8108-c548d5187f41.png)

I get this far, but it doesn't go any further. Log doesn't seem to show anything helpful either: https://pastebin.com/KHde3KwJ

Here are the mods I'm working with: flex-ltd.net/modpacks/vanilla.zip (it's about 300 megs, 1.12.1 pack)

Edit: Using the windows x64 binary if that helps.

**Comment by zlepper** [comment]
Please try the latest version, it should fix this issue. 

You can get the update from GitHub, or using the build in updater.

**Comment by Alaberti** [comment]
The updater didn't quite work, but I tried 2.02 - now I don't even get the continue button, it just stops after packing the mods. Then I tried the 2.03 version, but the build progress doesn't show any mods.

![203_test](https://user-images.githubusercontent.com/10929796/29802456-ecb02d9e-8c3a-11e7-8415-c49b7130f8f2.png)

**Comment by Alaberti** [comment]
If it matters, I'm using Google Chrome.
